google_ads_extractor:
  target: "{{ env_var('DBT_TARGET', 'dev') }}"
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_PROJECT_ID', 'gads-export-all') }}"
      dataset: "{{ env_var('DBT_DEV_DATASET', 'gads_reporting_scratch') }}"
      threads: 4
      location: EU
      priority: interactive
    stage:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_PROJECT_ID', 'gads-export-all') }}"
      dataset: "{{ env_var('DBT_STAGE_DATASET', 'gads_reporting_mart_stage') }}"
      threads: 4
      location: EU
      priority: interactive
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('DBT_PROJECT_ID', 'gads-export-all') }}"
      dataset: "{{ env_var('DBT_PROD_DATASET', 'gads_reporting_mart') }}"
      threads: 4
      location: EU
      priority: interactive
